# Working with Excel

In this section, we will import large datasets from an excel spreadsheet using `pandas`.

## Dataframe 

Dataframes is an object treated as a database.

In [6]:
import pandas as pd

data = pd.read_excel("D:/Downloads/vegetable.xlsx")
data.head()

   Order ID   Product    Category  Amount       Date         Country
0         1   Carrots  Vegetables    4270 2012-01-06   United States
1         2  Broccoli  Vegetables    8239 2012-01-07  United Kingdom
2         3    Banana       Fruit     617 2012-01-08   United States
3         4    Banana       Fruit    8384 2012-01-10          Canada
4         5     Beans  Vegetables    2626 2012-01-10         Germany

In [8]:
print(data)
type(data)

     Order ID   Product    Category  Amount       Date         Country
0           1   Carrots  Vegetables    4270 2012-01-06   United States
1           2  Broccoli  Vegetables    8239 2012-01-07  United Kingdom
2           3    Banana       Fruit     617 2012-01-08   United States
3           4    Banana       Fruit    8384 2012-01-10          Canada
4           5     Beans  Vegetables    2626 2012-01-10         Germany
..        ...       ...         ...     ...        ...             ...
208       209     Apple       Fruit    1777 2012-12-28          France
209       210     Beans  Vegetables     680 2012-12-28          France
210       211    Orange       Fruit     958 2012-12-29   United States
211       212   Carrots  Vegetables    2613 2012-12-29       Australia
212       213   Carrots  Vegetables     339 2012-12-30       Australia

[213 rows x 6 columns]

pandas.core.frame.DataFrame

Use `groupby` and `sum` to group categorial data and find the sum of amount of sold items.

In [28]:
vegetable_column = 'Category'
amount_sold = 'Amount'
data.groupby(vegetable_column)[amount_sold].sum()

Category
Fruit         693069
Vegetables    336665
Name: Amount, dtype: int64

- `head()` allows us to read the first few rows of the data set.
- `type()` returns the type of the object (dataframe)
- u can also print the full list of the data set with `print()`

In [21]:
data.describe()

         Order ID       Amount                           Date
count  213.000000   213.000000                            213
mean   107.000000  4834.431925  2012-06-26 17:00:50.704225280
min      1.000000   107.000000            2012-01-06 00:00:00
25%     54.000000  2417.000000            2012-04-01 00:00:00
50%    107.000000  4781.000000            2012-06-04 00:00:00
75%    160.000000  7223.000000            2012-09-19 00:00:00
max    213.000000  9990.000000            2012-12-30 00:00:00
std     61.631972  2765.396708                            NaN

`describe()` returns descriptive statistics such as mean, standard deviation, min and max values, as well as the quartiles. U can also output additional statistical data as follow:

In [20]:
data.corr(numeric_only = True)

          Order ID    Amount
Order ID  1.000000 -0.001131
Amount   -0.001131  1.000000